// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'specifications',
    {
      type: 'autogenerated',
      dirName: 'specifications',
    },
  ],
  standards: [
    'standards',
    {
      type: 'autogenerated',
      dirName: 'standards',
    },
  ],
  checklists: [
    'checklists',
    {
      type: 'autogenerated',
      dirName: 'checklists',
    },
  ],
  lisp: [
    'lisp',
    {
      type: 'autogenerated',
      dirName: 'lisp',
    },
  ],
};

module.exports = sidebars;
